services:
  backend:
    image: ijoaog/flexcommerce-backend:latest 
    container_name: flexcommerce-backend-1
    expose:
      - "3003"
    restart: always
    env_file:
      - ./backend/.env.production
    volumes:
      - flexcommerce-backend-cache:/root/.npm
    networks:
      - web

  frontend:
    image: ijoaog/flexcommerce-frontend:latest
    container_name: flexcommerce-frontend-1
    expose:
      - "3000"
    restart: always
    env_file:
      - ./frontend/.env.production
    volumes:
      - flexcommerce-frontend-cache:/root/.npm
    networks:
      - web

volumes:
  flexcommerce-backend-cache:
  flexcommerce-frontend-cache:

networks:
  web:
    external: true
