services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: backend-container
    ports:
      - "3003:3003"
    volumes:
      - ./backend:/app
      # Monta node_modules para evitar sobrescrever os módulos instalados dentro do container
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run start:dev
    networks:
      - app-network
      - shared-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  shared-network:
    external: true