FROM node:20-alpine

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

# Expõe a porta que o Nest usa
EXPOSE 3003

# Variável para forçar o watch funcionar no Docker
ENV CHOKIDAR_USEPOLLING=true

CMD ["npm", "run", "start:dev"]
